version: '2'
services:
  db:
    image: mdillon/postgis:latest
    volumes:
      - './.data/db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: farmos
      POSTGRES_PASSWORD: farmos

