version: '2'
services:
  db:
    image: mysql:latest
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: farmos
      MYSQL_DATABASE: farmos
      MYSQL_USER: farmos
      MYSQL_PASSWORD: farmos

  www:
    depends_on:
      - db
    image: farmos/farmos:docker
    volumes:
      - "./.data/www:/var/www/html"
    links:
      - db
    ports:
      - "80:80"
    restart: always
    environment:
      MYSQL_HOST: db:3306
      MYSQL_ROOT_PASSWORD: farmos
      MYSQL_DATABASE: farmos
      MYSQL_USER: farmos
      MYSQL_PASSWORD: farmos

