version: '2'
services:
  db:
    image: mariadb:latest
    volumes:
      - './.data/db:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: farmos
      MYSQL_DATABASE: farmos
      MYSQL_USER: farmos
      MYSQL_PASSWORD: farmos

  www:
    depends_on:
      - db
    image: farmos/farmos:7.x-1.0-rc1
#    image: farmos/farmos:7.x-1.x
    volumes:
      - './.data/www:/var/www/html'
    links:
      - db
    ports:
      - '80:80'
    environment:
      FARMOS_DEV: 'true'
