site_name: farmOS 2.x
nav:
  - farmOS: index.md
  - Hosting:
      - 1.x Migration: hosting/migration.md
  - API:
    - Introduction: api/index.md
    - Authentication: api/authentication.md
    - Changes: api/changes.md
  - Development:
    - Environment:
      - Getting started: development/environment/index.md
      - Docker: development/environment/docker.md
      - PostgreSQL: development/environment/postgresql.md
      - Drush: development/environment/drush.md
      - Composer: development/environment/composer.md
      - Debugging: development/environment/debug.md
      - Automated tests: development/environment/tests.md
      - Coding standards: development/environment/code.md
    - Module:
      - OAuth: development/module/oauth.md
      - Roles: development/module/roles.md
theme: readthedocs
