site_name: farmOS Documentation
site_url: http://8x-2x.farmos.org
site_favicon: favicon.ico
repo_url: https://github.com/farmOS/farmOS
copyright: <p><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">farmOS.org</span> content is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.<br />farmOS is a <a href="http://farmOS.org/community/trademark">registered trademark</a> of <a href="http://mstenta.net">Michael Stenta</a></p>.
google_analytics: ['UA-56974603-1', 'farmos.org']
pages:
- Home: index.md
- Development:
  - Docker: dev/docker.md
  - Theme: dev/theme.md
  - Dependencies: dev/dependencies.md
theme: readthedocs
