site_name: farmOS 2.x Docs
nav:
  - Data model:
    - Introduction: model/index.md
    - Record types:
      - Assets: model/type/asset.md
      - Logs: model/type/log.md
      - Quantities: model/type/quantity.md
      - Terms: model/type/term.md
      - Plans: model/type/plan.md
      - Users: model/type/user.md
    - Logic:
      - Location: model/logic/location.md
      - Group membership: model/logic/group.md
      - Inventory: model/logic/inventory.md
    - Conventions: model/convention/index.md
  - Development:
    - API:
      - Introduction: development/api/index.md
      - Authentication: development/api/authentication.md
      - Changes: development/api/changes.md
    - Module:
      - Getting started: development/module/index.md
      - Entities: development/module/entities.md
      - Fields: development/module/fields.md
      - OAuth: development/module/oauth.md
      - Roles: development/module/roles.md
      - Updates: development/module/updates.md
      - Services: development/module/services.md
    - Environment:
      - Getting started: development/environment/index.md
      - HTTPS: development/environment/https.md
      - Updating: development/environment/update.md
      - Docker: development/environment/docker.md
      - PostgreSQL: development/environment/postgresql.md
      - Drush: development/environment/drush.md
      - Composer: development/environment/composer.md
      - Debugging: development/environment/debug.md
      - Automated tests: development/environment/tests.md
      - Coding standards: development/environment/code.md
      - Documentation: development/environment/documentation.md
  - Hosting:
    - Introduction: hosting/index.md
    - Installing: hosting/install.md
    - Updating: hosting/update.md
    - Email: hosting/email.md
    - 1.x Migration: hosting/migration.md
theme:
  name: material
  palette:
    primary: green
    accent: orange
  icon:
    logo: material/leaf
  favicon: favicon.ico
markdown_extensions:
  - toc:
      permalink: true
copyright: This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>. farmOS is a <a href="/community/trademark">registered trademark</a> of <a href="http://mstenta.net">Michael Stenta</a>
