site_name: farmOS Docs
nav:
  - User Guide:
    - Introduction: guide/index.md
    - Mapping locations: guide/mapping.md
    - Managing assets: guide/assets.md
    - Logging events: guide/logs.md
    - Movements and location: guide/location.md
    - Quantities: guide/quantities.md
    - Inventory: guide/inventory.md
    - People: guide/people.md
    - Quick forms: guide/quick.md
    - Importing data: guide/import.md
    - Exporting data: guide/export.md
  - Data model:
    - Introduction: model/index.md
    - Record types:
      - Assets: model/type/asset.md
      - Logs: model/type/log.md
      - Quantities: model/type/quantity.md
      - Data streams: model/type/data_stream.md
      - Files: model/type/file.md
      - Terms: model/type/term.md
      - Plans: model/type/plan.md
      - Users: model/type/user.md
    - Logic:
      - Location: model/logic/location.md
      - Group membership: model/logic/group.md
      - Inventory: model/logic/inventory.md
    - Conventions: model/convention/index.md
  - Development:
    - API:
      - Introduction: development/api/index.md
      - Authentication: development/api/authentication.md
      - Changes: development/api/changes.md
    - Module:
      - Getting started: development/module/index.md
      - Quick forms: development/module/quick.md
      - Entities: development/module/entities.md
      - Fields: development/module/fields.md
      - Maps: development/module/maps.md
      - OAuth: development/module/oauth.md
      - Roles: development/module/roles.md
      - Services: development/module/services.md
      - Data streams: development/module/data_stream.md
      - CSV importers: development/module/csv.md
      - Updates: development/module/updates.md
    - Environment:
      - Getting started: development/environment/index.md
      - HTTPS: development/environment/https.md
      - Updating: development/environment/update.md
      - Docker: development/environment/docker.md
      - PostgreSQL: development/environment/postgresql.md
      - Drush: development/environment/drush.md
      - Composer: development/environment/composer.md
      - Debugging: development/environment/debug.md
      - Automated tests: development/environment/tests.md
      - Coding standards: development/environment/code.md
      - Documentation: development/environment/documentation.md
  - Hosting:
    - Introduction: hosting/index.md
    - Installing: hosting/install.md
    - Updating: hosting/update.md
    - Composer: hosting/composer.md
    - Email: hosting/email.md
    - Translations: hosting/localization.md
    - v1 Migration: hosting/migration.md
theme:
  name: material
  palette:
    primary: green
    accent: orange
