site_name: farmOS.org
site_url: http://farmos.org
repo_url: https://github.com/farmOS
site_favicon: favicon.ico
copyright: <p><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">farmOS.org</span> content is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.<br />farmOS is a <a href="/community/trademark">registered trademark</a> of <a href="http://mstenta.net">Michael Stenta</a></p>.
google_analytics: ['UA-56974603-1', 'farmos.org']
pages:
- Home: index.md
- User Guide:
    - Introduction: guide/index.md
    - Mapping your farm: guide/areas.md
    - Logging events: guide/logs.md
    - Managing assets:
        - Introduction: guide/assets/index.md
    - Movements and location: guide/location.md
    - People: guide/people.md
    - Demos: guide/demos.md
- Hosting:
    - Getting started: hosting/index.md
    - Installing: hosting/installing.md
    - Updating: hosting/updating.md
    - Google Maps: hosting/googlemaps.md
- Development:
    - Drupal: development/drupal.md
    - Projects: development/projects.md
    - Issue Queues: development/issue-queues.md
    - Architecture: development/architecture.md
    - Update Safety: development/update-safety.md
    - Docker: development/docker.md
- Community:
    - Contribute: community/contribute.md
    - Monthly Call: community/monthly-call.md
    - Farms: community/farms.md
    - Maintainers: community/maintainers.md
    - Supporters: community/supporters.md
    - Press: community/press.md
    - Trademark: community/trademark.md
- FAQ: faq.md
theme: yeti

