version: '3'
services:
  www:
    image: farmos/farmos:3.x-dev
    volumes:
      - './www:/opt/drupal'
    environment:
      FARMOS_FS_READY_SENTINEL_FILENAME: /opt/drupal/www-container-fs-ready
      SIMPLETEST_DB: $DB_URL
      XDEBUG_MODE: 'off'

  chrome:
    # Tests are failing on later versions of this image.
    # See https://github.com/farmOS/farmOS/issues/514
    image: selenium/standalone-chrome:4.1.2-20220217
