version: '2'
services:
  db:
    image: postgis/postgis:latest
    volumes:
      - './db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
    restart: unless-stopped
