# Schema for the asset location views field handler.
views.field.asset_location:
  type: views.field.field
  label: 'Asset location field handler'

# Schema for the asset location third party settings.
asset.type.*.third_party.farm_location:
  type: mapping
  label: 'Location settings'
  mapping:
    is_location:
      type: boolean
      label: 'Is a location'
    is_fixed:
      type: boolean
      label: 'Is fixed'

# Schema for the log location third party settings.
log.type.*.third_party.farm_location:
  type: mapping
  label: 'Location settings'
  mapping:
    is_movement:
      type: boolean
      label: 'Is a movement'
