name: Run 2.x PHPUnit tests
on:
  push:
    branches:
      - '2.x'

jobs:
  build:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set FARMOS_VERSION environment variable
        run: echo ::set-env name=FARMOS_VERSION::${GITHUB_REF:11}
      - name: Build farmOS 2.x Docker image
        run: docker build --build-arg FARMOS_REPO=https://github.com/${GITHUB_REPOSITORY} --build-arg FARMOS_VERSION=${FARMOS_VERSION} -t farmos/farmos:2.x docker
      # This builds the dev Docker image using the specified FARMOS_VERSION,
      # but notably it does NOT override the default PROJECT_VERSION, so the
      # farmOS Composer project 2.x branch is always used.
      - name: Build farmOS 2.x-dev Docker image
        run: docker build --build-arg FARMOS_REPO=https://github.com/${GITHUB_REPOSITORY} --build-arg FARMOS_VERSION=${FARMOS_VERSION} -t farmos/farmos:2.x-dev docker/dev
      - name: Create docker-compose.yml
        run: curl https://raw.githubusercontent.com/farmOS/farmOS/2.x/docker/docker-compose.development.yml -o docker-compose.yml
      - name: Start containers
        run: sudo docker-compose up -d
      - name: Wait 10 seconds
        run: sleep 10
      - name: Run PHPUnit tests
        run: sudo docker exec -i -u www-data farmos_www_1 phpunit --verbose --debug --group farm
      - name: Run PHP CodeSniffer
        run: sudo docker exec -i -u www-data farmos_www_1 phpcs /opt/drupal/web/profiles/farm
