name: Test Docker and Drush Make builds
on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Test Docker and Drush Make builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set FARMOS_BRANCH environment variable
        run: echo ::set-env name=FARMOS_BRANCH::${GITHUB_REF:11}
      - name: Build farmOS Docker image
        run: docker build -t farmos-dev --build-arg FARMOS_REPO=https://github.com/${GITHUB_REPOSITORY} --build-arg FARMOS_BRANCH=${FARMOS_BRANCH} docker/dev
      - name: Run farmOS Docker container
        run: docker run --rm -v /tmp/farmOS:/var/www/html farmos-dev true
      - name: Create artifact
        run: cd /tmp && tar -czf farmOS.tar.gz farmOS
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: farmOS-${{ env.FARMOS_BRANCH }}
          path: /tmp/farmOS.tar.gz
